apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    name: myapp-rc
    type: front-end
spec:
  template:
    metadata:
      name: myapp-rc
      labels:
        name: myapp-rc
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

replicas: 3
selector:
  matchLabels:
    type: front-end